// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggzlkxuieycxngiqyzbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnemxreHVpZXljeG5naXF5emJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjAzOTIsImV4cCI6MjA2NDUzNjM5Mn0.5WR2GbEmw0FC5XJDtIRMPsoJTCmmft8QPJeCPuemmcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);